#%RAML 1.0 Library
usage: A basic type in the agent subscription raml library

types:

  Timestamp:
    type: datetime
    example: 2016-10-28T16:41:41.090Z
    format: rfc3339

  HmrcService:
    description: The service to subscribe to
    type: string
    enum: [ mtd-sa ]

  LinkItem:
    displayName: Link Item
    description: An object containing a href property of a traversable link to a related resource
    type: object
    properties:
      href: string
    example: |
      {
        "href" : "/agencies/00010002-0003-0004-0005-000600070008"
      }


  LinkSection:
    displayName: Link Section
    description: Contains the LinkItems available from this resource
    type: object
    properties:
      self: LinkItem
      invitations?: LinkItem[]
      cancel?: LinkItem
      accept?: LinkItem
      reject?: LinkItem
    example: |
      {
        "self" : { "href" : "/agencies/00010002-0003-0004-0005-000600070008"},
        "cancel" : { "href" : "/agencies/00010002-0003-0004-0005-000600070008"}
      }


  Status:
    displayName: Statuses
    enum: [ pending, accepted, rejected ]
    type: string
    description: |
      The status of the current subscription request
      Status  | Meaning
      ------- | -------
      ```pending``` | The subscription request has been created, it has not been accepted or rejected by HMRC.
      ```accepted``` | HMRC has accepted the subscription, and has created the subscription identifier.
      ```rejected``` | HMRC has not accepted the subscription request.
