#%RAML 1.0
title: Agent Subscription
baseUri: https://gov.uk/agent-subscription
version: 0.0
mediaType: application/vnd.hmrc.1.0+json
description: An API for agencies to subscribe to services

uses: 
  subscriptions: modules/subscriptions.raml
/agencies/subscriptions
  post:
    description: Create a service subscription
    body:
      type: agencies.SubscriptionRequest
    responses:
      202:
        description: Subscription request has been received. The location header provides a URL where the request status can be checked.
        headers:
          Location:
            example: /agencies/subscriptions/00010002-0003-0004-0005-000600070008
      401:
        description: The agent must be authenticated and authorised (logged-in) to use this resource

/agencies/subscriptions/:subscriptionRequestId
  get:
    description: Check on the status of a subscription request.
    responses:
      200:
        description: Returns a previously submitted subscription request.
        body:
          type: subscriptions.SubscriptionRequest
      401:
        description: The agent must be authenticated and authorised (logged-in) to use this resource
      403:
        description: The agent is not permitted to view this subscription request
